import matplotlib as plt
import numpy as np
import os
from shapes import shapes



def chaos_game(corners, n_points, dim=3):
    """
    Precondition: 
	corners: is a nupmy array with the coordinates (of dimensions=dim) of the
    	corners.
    	n_points: is the number of poitns to be generated via the the chaose game.
    	dim: is the number of dimensions each points will be defined by.
	Postcondition: Returns a numpy array of the n_points generated by the chaos
    	game.
	"""
    points = np.zeros((n_points, dim))
    np.mean(corners, axis=0)
    
    print("Generating...")
    for i in range(1, n_points):
        next_corner = corners[np.random.randint(len(corners))]
        points[i] = 0.5 * (points[i-1] + next_corner)

    return points

def save_gen(file_path, points, corners, metadata):
    """
    Preconditions:
    file_path : str
        Path relative to data root (folder + filename).
    arrays : dict
        Dictionary of numpy arrays to save (e.g. {"points": pts, "corners": c})
    metadata : dict
        Dictionary of metadata (scalars, strings, small arrays).

    helper functions: None

    Save generated data and metadata to disk.

    Postcondition: None
    """
    INTERNAL_BASE = "/Users/tobiaswatters/Desktop/DSproj/point_data"

    full_path = os.path.join(INTERNAL_BASE, file_path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)

    np.savez(
        full_path,
        points=points,
        corners=corners,
        **metadata
    )

def regular_n_polygon(n):
    """
    param: n is the number of sides of the n polygon.

    helper functions: None
    
    Returns corners of a regular n-sided polygon,
    scaled to fit in the unit square
    """
    angles = np.linspace(0, 2*np.pi, n, endpoint=False) # regular polygon on unit circle

    angles += np.pi / n - np.pi / 2 # rotate so base is horizontal

    x = np.cos(angles)
    y = np.sin(angles)
    corners = np.column_stack((x, y, np.array([0,0,0])))

    min_x = corners[:,0].min()    # uniform scale so width = 1
    max_x = corners[:,0].max()
    scale = 1 / (max_x - min_x)
    corners *= scale

    corners[:,0] -= corners[:,0].min()    # shift so leftmost x = 0

    corners[:,1] -= corners[:,1].min()    # shift so base touches y = 0

    return corners

def gen_tetrahedron(n_points):
	base_corners = regular_n_polygon(3)
	corners = np.vstack([base_corners, np.array([0.5, 0.28867513, 0.81649658])])

	points = chaos_game(corners, n_points)

	metadata = {
		"n": 4,
		"dim": 3,
		"n_points": n_points
	}

	return corners, points, metadata

def gen_unit_shape(n_corners, n_points):
    corners = shapes[n_corners][1]
    points = chaos_game(corners,n_points)
    print(f"Finish generating n={n_corners}")
    metadata = {
        "shape": shapes[n_corners][0],
        "n": n_corners,
        "dim": 3,
        "n_points": n_points
    }
    full_path = f"/Users/tobiaswatters/Desktop/DSproj/point_data/{shapes[n_corners][0]}.npz"
    save_gen(full_path, points, corners, metadata)

    ## Debugging:
    if os.path.exists(full_path):
        data = np.load(full_path)
        if "points" in data and len(data["points"]) == n_points:
            print("File verified.")
        else:
            raise ValueError("Data not saved correctly.")
    else:
        raise ValueError("File not created correctly.")





if __name__ == "__main__":
    for n_corners in [4, 5, 6, 8, 12, 20]:
        gen_unit_shape(n_corners, 5_000_000)




